title: "Rok Sim"
description: ""
baseurl: ""
url: https://rsim89.github.io/

theme: cvless

# site settings
taglong: Rok Sim's personal webpage
tagshort: RokSim

# author settings
author:
  name: Rok Sim
  email: rsim@email.sc.edu
photo: assets/files/roksim.jpg
address: Foobar Hall 1.23
phone: +1 803 201 0717

exclude:
  - demo/
  - cvless.gemspec
  - LICENSE
  - README.md
  - screenshot.png

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  style: compressed
  sourcemap: never

feed:
  path: atom.xml

autopages:
  enabled: false

pagination:
  enabled: true
  per_page: 1
  sort_reverse: true
  permalink: /:num/
  title: ":title &middot; Page :num"
